# Generated by Django 5.0.8 on 2025-03-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentimage',
            name='image',
            field=models.ImageField(upload_to='studentimage/'),
        ),
    ]
