# Generated by Django 5.0.8 on 2025-03-27 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_studentimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminimage',
            old_name='admin',
            new_name='teacher',
        ),
    ]
