# Generated by Django 5.0.8 on 2025-03-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_rename_admin_adminimage_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='question_number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
